# necessary for kubeadm-dind
#dist: xenial

language: node_js
node_js: 8
dist: trusty

env:
  matrix:
    - SCRIPTS="lint.sh webpack.sh"
      LAYERS="core bash-like core-support field-installed-plugins editor"
      NEEDS_ELECTRON=true
      NEEDS_IBMCLOUD_CLI=true # see plugins/plugin-bash-like/src/test/bash-like/bash-like.ts

    - LAYERS="openwhisk1 openwhisk3 grid"
      NEEDS_ELECTRON=true
      NEEDS_OPENWHISK=true

    - LAYERS="openwhisk2 openwhisk4"
      NEEDS_ELECTRON=true
      NEEDS_OPENWHISK=true
      NEEDS_OPENWHISK_API_GATEWAY=true
      NEEDS_OPENWHISK_NODEJS8=true
      NEEDS_OPENWHISK_JAVA8=true
      NEEDS_SECOND_OPENWHISK_AUTH=true # see plugins/plugin-openwhisk/src/test/openwhisk2/auth.ts

    - LAYERS="composer1 composer2 composer3"
      NEEDS_ELECTRON=true
      NEEDS_OPENWHISK=true

    - LAYERS="k8s"
      NEEDS_ELECTRON=true
      NEEDS_HEADLESS=true
      NEEDS_KUBERNETES=true

    - LAYERS="HEADLESS"
      NEEDS_HEADLESS=true
      NEEDS_OPENWHISK=true
      NEEDS_KUBERNETES=true

  global:
    - TRAVIS_KUBE_VERSION=1.12 # kubeadm-dind
    - TEST_ORG=testorg
    - TEST_SPACE=testspace
    - LOCAL_OPENWHISK=true # allows e.g. openwhisk/src/test/openwhisk1/headless to avoid trying to host set <not-local>
    - IGNORE_CERTS=true # apache-composer needs this, because it doesn't obey INSECURE_SSL in wskprops
    - PATH=bin:$PATH
    - NO_MAC_DMG_INSTALLER=`[[ $TRAVIS_OS_NAME != osx ]] && echo true` # we can't build macOS DMG files in linux travis :(
    - WINDOW_WIDTH=1400                   # ! important ! so that clicks don't fail due to elements being off-viewport
    - WINDOW_HEIGHT=1050                  # ! ibid !
    - TEST_FROM_BUILD="${TRAVIS_BUILD_DIR}/clients/default/dist/electron/$(case $TRAVIS_OS_NAME in 'linux' ) echo Kui-linux-x64/Kui;; 'osx' ) echo Kui-darwin-x64/Kui.app/Contents/MacOS/Kui;; esac)" # test against a specific dist build
    - BUILD_ENV=production                # please note: used in dist/electron/build.sh with npm prune --production

matrix:
  include:
  - os: osx
    if: repo = ibm/kui

before_install: echo $TRAVIS_REPO_SLUG
install: ./tools/travis/test/install.sh
script: ./tools/travis/test/script.sh
after_success: ./tools/travis/publishers/cos.sh

notifications:
  webhooks:
    - https://openwhisk.ng.bluemix.net/api/v1/web/nickm_production/travis-for-kui/done.json
